### ISSUE TITLE
Deploy the project to production

### ISSUE THREAD

**Issue by gaaliciA1990** [gaaliciA1990/GameNewsNetwork_ChatGPT#10]
Once all development is completed, launch the product into production on [SERVICE]

- [x] Deploy site locally on giroro
- [x] Deploy site publicly (official Launch)

**Comment by CRamsan** [comment]
I looked into this and it seems like the easiest way to start would be to launch the website in our own server. @gaaliciA1990 as the repo owner you will have to configure some runners in our server. Ping me so we can do this togethee.

**Comment by gaaliciA1990** [comment]
Note: System set up on giroro, however service is failing due to PORT error. 
`Use command line options -port/-sslPort or configure connectors in application.conf`

**Comment by gaaliciA1990** [comment]
Successfully launched the site on giroro. Port issue fixed with `override.conf`
