### ISSUE TITLE
SERVICE IS DOWN

### ISSUE THREAD

**Issue by CRamsan** [gaaliciA1990/GameNewsNetwork_ChatGPT#33]
**Describe the bug**
I am trying to access https://192.168.1.151:8080/ but I am getting an error page. I think the server is down.

**To Reproduce**

1.  Go to https://192.168.1.151:8080/

**Expected behavior**
The website

**Additional context**
:(

**Comment by gaaliciA1990** [comment]
Not an issue, server restarted and hasn't gone down again in 5 days.
